steps:
  # Create Artifact Registry repository if it doesn't exist
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud artifacts repositories describe followupai-express --location=us-central1 2>/dev/null || \
        gcloud artifacts repositories create followupai-express --repository-format=docker --location=us-central1 --description="Express backend images"

  # Build the Express container (use SHORT_SHA or 'latest' as fallback)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/followupai-express/followupai-express:latest'
      - '-f'
      - 'cloud-run-express/Dockerfile'
      - '.'
    timeout: '1200s'

  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/followupai-express/followupai-express:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'followupai-express'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/followupai-express/followupai-express:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'
      - '--timeout'
      - '60s'
      - '--set-env-vars'
      - 'NODE_ENV=production,CORS_ORIGINS=https://followupai.io,APP_URL=https://followupai.io'
      - '--set-secrets'
      - 'DATABASE_URL=DATABASE_URL:latest,STYTCH_PROJECT_ID=STYTCH_PROJECT_ID:latest,STYTCH_SECRET=STYTCH_SECRET:latest,SESSION_SECRET=SESSION_SECRET:latest'
    timeout: '600s'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/followupai-express/followupai-express:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1800s'
