# Followup AI Backend - Google Cloud Build Configuration
#
# This configuration builds and deploys the backend to Cloud Run with GPU support.
#
# Prerequisites:
# 1. Enable Cloud Build, Cloud Run, Artifact Registry, and Secret Manager APIs
# 2. Create secrets in Secret Manager: DATABASE_URL, STYTCH_PROJECT_ID, STYTCH_SECRET, OPENAI_API_KEY
# 3. Grant Cloud Build service account access to secrets and Cloud Run
#
# Trigger: Push to main branch or manual trigger
# 
# Usage:
#   gcloud builds submit --config=gcp/cloudbuild.yaml .

substitutions:
  _REGION: us-central1
  _SERVICE_NAME: followup-backend
  _REPOSITORY: followup-ai
  _MIN_INSTANCES: '1'
  _MAX_INSTANCES: '10'
  _MEMORY: '8Gi'
  _CPU: '4'
  _GPU_TYPE: nvidia-l4
  _GPU_COUNT: '1'
  _TIMEOUT: '60'
  _CONCURRENCY: '80'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

steps:
  # Step 1: Build Docker image with cache
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --cache-from ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest \
          -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA} \
          -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest \
          -f gcp/Dockerfile \
          .

  # Step 2: Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}'
    waitFor:
      - 'build'

  # Step 3: Deploy to Cloud Run with GPU
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--min-instances=${_MIN_INSTANCES}'
      - '--max-instances=${_MAX_INSTANCES}'
      - '--memory=${_MEMORY}'
      - '--cpu=${_CPU}'
      - '--gpu=${_GPU_COUNT}'
      - '--gpu-type=${_GPU_TYPE}'
      - '--timeout=${_TIMEOUT}'
      - '--concurrency=${_CONCURRENCY}'
      - '--set-env-vars=ENV=production,LOG_LEVEL=INFO'
      - '--set-secrets=DATABASE_URL=DATABASE_URL:latest,STYTCH_PROJECT_ID=STYTCH_PROJECT_ID:latest,STYTCH_SECRET=STYTCH_SECRET:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest,OPENAI_BAA=OPENAI_BAA:latest,OPENAI_ZDR=OPENAI_ZDR:latest'
      - '--service-account=followup-backend@${PROJECT_ID}.iam.gserviceaccount.com'
    waitFor:
      - 'push'

  # Step 4: Get service URL and configure traffic
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'traffic'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run services update-traffic ${_SERVICE_NAME} \
          --region=${_REGION} \
          --to-latest
        
        echo "Deployment complete!"
        gcloud run services describe ${_SERVICE_NAME} \
          --region=${_REGION} \
          --format='value(status.url)'
    waitFor:
      - 'deploy'

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'

timeout: '1800s'
